const ProductsTypes = {
    FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
    FETCH_PRODUCTS_SUCCES: "FETCH_PRODUCTS_SUCCES",
    FETCH_PRODUCTS_FAILURE: "FETCH_PRODUCTS_FAILURE",

    FETCH_PRODUCT_DETAIL_START: "FETCH_PRODUCT_DETAIL_START",
    FETCH_PRODUCT_DETAIL_SUCCESS: "FETCH_PRODUCT_DETAIL_SUCCESS",
    FETCH_PRODUCT_DETAIL_FAILURE: "FETCH_PRODUCT_DETAIL_FAILURE",
};

export default ProductsTypes;
